TIME_ONE = "body > div:nth-child(1) > div > div.wc-WebConsoleModule_SiteContainer > div.wc-PageView > div > div > div.wcl-PageContainer.wcl-PageContainer_State1.wcl-PageContainer-scrollable > div.wcl-PageContainer_Colcontainer > div > div > div.cm-CouponModule > div > div:nth-child(2) > div.gl-MarketGroup_Wrapper > div > div > div:nth-child(1)"
DIV_INPUT_ONE = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div.bss-BetslipStandardModule-wide.bsm-BetslipStandardModule.bss-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_Expanded.bss-BetslipStandardModule_Expanded > div > div.bss-StandardBetslip_ContentWrapper > div.bss-StandardBetslip_Content > div > div:nth-child(1) > div > div > div.bss-NormalBetItem_Content > div.bss-NormalBetItem_ContentWrapper > div.bss-StakeBox.bss-StakeBox_MouseMode > div.bss-StakeBox_StakeAndReturn > div > div.bss-StakeBox_StakeValue.bss-StakeBox_StakeValue-empty"
INPUT_ONE = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div.bss-BetslipStandardModule-wide.bsm-BetslipStandardModule.bss-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_Expanded.bss-BetslipStandardModule_Expanded > div > div.bss-StandardBetslip_ContentWrapper > div.bss-StandardBetslip_Content > div > div:nth-child(1) > div > div > div.bss-NormalBetItem_Content > div.bss-NormalBetItem_ContentWrapper > div.bss-StakeBox.bss-StakeBox_MouseMode > div.bss-StakeBox_StakeAndReturn > div > input"

TIME_TWO = "body > div:nth-child(1) > div > div.wc-WebConsoleModule_SiteContainer > div.wc-PageView > div > div > div.wcl-PageContainer.wcl-PageContainer_State1.wcl-PageContainer-scrollable > div.wcl-PageContainer_Colcontainer > div > div > div.cm-CouponModule > div > div:nth-child(2) > div.gl-MarketGroup_Wrapper > div > div > div:nth-child(3)"
DIV_INPUT_TWO = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div.bss-BetslipStandardModule-wide.bsm-BetslipStandardModule.bss-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_Expanded.bss-BetslipStandardModule_Expanded > div > div.bss-StandardBetslip_ContentWrapper > div.bss-StandardBetslip_Content > div > div:nth-child(2) > div > div > div.bss-NormalBetItem_Content > div.bss-NormalBetItem_ContentWrapper > div.bss-StakeBox.bss-StakeBox_MouseMode > div.bss-StakeBox_StakeAndReturn > div > div.bss-StakeBox_StakeValue.bss-StakeBox_StakeValue-empty"
INPUT_TWO = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div.bss-BetslipStandardModule-wide.bsm-BetslipStandardModule.bss-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_Expanded.bss-BetslipStandardModule_Expanded > div > div.bss-StandardBetslip_ContentWrapper > div.bss-StandardBetslip_Content > div > div:nth-child(2) > div > div > div.bss-NormalBetItem_Content > div.bss-NormalBetItem_ContentWrapper > div.bss-StakeBox.bss-StakeBox_MouseMode > div.bss-StakeBox_StakeAndReturn > div > input"

CARDENETA = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div > div > div.bss-StandardHeader > div"
FAZER_APOSTA = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div.bss-BetslipStandardModule-wide.bsm-BetslipStandardModule.bss-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_Expanded.bss-BetslipStandardModule_Expanded > div > div.bss-Footer > div"



CLOSE_MESSAGES = "body > div.pm-PushTargetedMessageOverlay_CurrentSize-1.pm-PushGraphicContainer_CurrentSize-1.pm-PushGraphicContainer.pm-PushTargetedMessageOverlay > div.pm-PushTargetedMessageOverlay_CloseButton"