TIME_ONE = "div.gl-Participant:nth-child(1)"
DIV_INPUT_ONE = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div.bss-BetslipStandardModule-wide.bsm-BetslipStandardModule.bss-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_Expanded.bss-BetslipStandardModule_Expanded > div > div.bss-StandardBetslip_ContentWrapper > div.bss-StandardBetslip_Content > div > div:nth-child(1) > div > div > div.bss-NormalBetItem_Content > div.bss-NormalBetItem_ContentWrapper > div.bss-StakeBox.bss-StakeBox_MouseMode > div.bss-StakeBox_StakeAndReturn > div > div.bss-StakeBox_StakeValue.bss-StakeBox_StakeValue-empty"
INPUT_ONE = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div.bss-BetslipStandardModule-wide.bsm-BetslipStandardModule.bss-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_Expanded.bss-BetslipStandardModule_Expanded > div > div.bss-StandardBetslip_ContentWrapper > div.bss-StandardBetslip_Content > div > div:nth-child(1) > div > div > div.bss-NormalBetItem_Content > div.bss-NormalBetItem_ContentWrapper > div.bss-StakeBox.bss-StakeBox_MouseMode > div.bss-StakeBox_StakeAndReturn > div > input"

TIME_TWO = "div.gl-Participant:nth-child(3)"
DIV_INPUT_TWO = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div.bss-BetslipStandardModule-wide.bsm-BetslipStandardModule.bss-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_Expanded.bss-BetslipStandardModule_Expanded > div > div.bss-StandardBetslip_ContentWrapper > div.bss-StandardBetslip_Content > div > div:nth-child(2) > div > div > div.bss-NormalBetItem_Content > div.bss-NormalBetItem_ContentWrapper > div.bss-StakeBox.bss-StakeBox_MouseMode > div.bss-StakeBox_StakeAndReturn > div > div.bss-StakeBox_StakeValue.bss-StakeBox_StakeValue-empty"
INPUT_TWO = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div.bss-BetslipStandardModule-wide.bsm-BetslipStandardModule.bss-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_Expanded.bss-BetslipStandardModule_Expanded > div > div.bss-StandardBetslip_ContentWrapper > div.bss-StandardBetslip_Content > div > div:nth-child(2) > div > div > div.bss-NormalBetItem_Content > div.bss-NormalBetItem_ContentWrapper > div.bss-StakeBox.bss-StakeBox_MouseMode > div.bss-StakeBox_StakeAndReturn > div > input"

CARDENETA = ".bss-DefaultContent"
FAZER_APOSTA = "body > div:nth-child(1) > div > div:nth-child(2) > div > div > div.bss-BetslipStandardModule-wide.bsm-BetslipStandardModule.bss-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_MouseMode.bsm-BetslipStandardModule_Expanded.bss-BetslipStandardModule_Expanded > div > div.bss-Footer > div"
AO_VIVO = "div.hm-MainHeaderCentreWide_Link:nth-child(2) > div:nth-child(1)"


CLOSE_MESSAGES = "body > div.pm-PushTargetedMessageOverlay_CurrentSize-1.pm-PushGraphicContainer_CurrentSize-1.pm-PushGraphicContainer.pm-PushTargetedMessageOverlay > div.pm-PushTargetedMessageOverlay_CloseButton"